### ISSUE TITLE
Too many imports

### ISSUE THREAD

**Issue by ufukomer** [take-cheeze/dep-dl#5]
I got an error like this:

<img width="1360" alt="screen shot 2019-02-13 at 2 51 21 pm" src="https://user-images.githubusercontent.com/7649229/52709829-de27cf80-2f9e-11e9-9f6f-7821f7ca8c57.png">

**Comment by take-cheeze** [comment]
@ufukomer Thanks for the report.
Should be fixed in master. Please check it out.
It was helpful if you paste me the text of the errors.

**Comment by ufukomer** [comment]
@take-cheeze Oh! Sorry for ss. It is working perfectly now. Thank you!
